### ISSUE TITLE
Agenix wrapper errors out for flakes that exist as a subdirectory in a git repository

### ISSUE THREAD

**Issue by JustinLex** [oddlama/agenix-rekey#12]
My homelab infrastructure monorepo has the "nodes" nix.flake under the nodes/ subdirectory. When I try to run the agenix wrapper in this subdirectory, it dies and gives the error "error: Could not determine location of your project's flake.nix. Please run this at or below your main directory containing the flake.nix." This is happening even though my pwd is the nodes/ directory with the nix.flake in it.

The bug seems to be here: 

https://github.com/oddlama/agenix-rekey/blob/e02a57e08224422934974f19853d4d70ed7eaaaa/nix/package.nix#L21

`USER_FLAKE_DIR` is being set to the output of `git rev-parse --show-toplevel`, which is the parent git repository, not the subdirectory with my flake.

The agenix wrapper should either:
* try both git toplevel and pwd before dying
or
* search for the flake recursively upwards from pwd until it reaches git toplevel

**Comment by oddlama** [comment]
Sounds good, I can add that when I have some time next month :)

**Comment by oddlama** [comment]
I've implemented recursive upward search, can you try whether that solves your problem?
