### ISSUE TITLE
Feature request: add option to use `age` instead of `rage`

### ISSUE THREAD

**Issue by ersinakinci** [oddlama/agenix-rekey#14]
As mentioned in #13, `rage` doesn't work for me and maybe others.

Would be great if we could get an option to use `age` instead.

**Comment by oddlama** [comment]
I've just added a switch to make this possible. Would you be able to test whether it works as you'd expect it to?
The readme has a (very) small [section about this](https://github.com/oddlama/agenix-rekey?tab=readme-ov-file#using-age-instead-of-rage).

**Comment by oddlama** [comment]
I'll close this for now, just comment under the closed issue if anything comes up.

**Comment by ersinakinci** [comment]
@oddlama thank you so much! I will test in the next few days once I get the chance to use my NixOS box again. Really, really appreciate your responsiveness and the new feature.

**Comment by ersinakinci** [comment]
@oddlama I'm finally getting around to testing your feature.

How would you specify the `age` package when using `nix shell` or a dev shell?

**Comment by oddlama** [comment]
In the same way. The `agenix` script consumes the agenix-rekey output of your flake to know the configuration, so whatever is set there will be used.

**Comment by ersinakinci** [comment]
Amazing! It all works. All I had to do is run `nix develop` after adding agenix-rekey to my system's default dev shell as explained in the readme, and it picked up on the `agePackage = p: p.age;` config.

Thanks again!
