### ISSUE TITLE
Docs: What goes wrong if you use a different package set in a generator?

### ISSUE THREAD

**Issue by plaidfinch** [oddlama/agenix-rekey#19]
The documentation states, regarding the `pkgs` argument to a generator script:

> The package set for the host that is running the generation script. Don't use any other packgage set in the script!

I'm still a little unclear about why this is so important. Is this just because you shouldn't use a package set for a host on a different architecture, or does it need to be *the exact same* package set that is passed through here, for some reason I don't understand?

My concrete problem is that I'm developing on a flake that has some locally defined packages not present in nixpkgs, and I'd like to use them in a generator script. Should I expect anything to go wrong if I use them directly, so long as I am using references to packages that are the same `system` as the rekeying host?

It would be helpful to add some more commentary about the "why" of this directive. It's expressed very strongly, so I figure you have good reason for stating it, but even after looking through the source code of `agenix-rekey` I'm still scratching my head.

**Comment by oddlama** [comment]
The `pkgs` passed to the generator functions is always guaranteed to be for the system that is running the rekeying operations. When writing a generator definition in a host configuration, most people would just reuse the pkgs set that they got from the nixos module if they needed one. I wanted to be very clear that this would be an error. If you have an x86_64-linux host but are rekeying on a aarch64-linux, then the script would try to execute a binary for a different architecture.

Maybe the "Don't use any other ..." is too strongly worded, it should maybe read "Don't use any other package set in the script, except if you know what you are doing".

Regarding your issue: If you want to use a specific package set from your flake, then you can just pass it in via the `pkgs` argument of `agenix-rekey.configure`. Each generator script will be called using the corresponding package set. [See here for the definition](https://github.com/oddlama/agenix-rekey/blob/8da0392e75373711604a07907de25ec9d5277384/flake.nix#L47-L48)

```nix
agenix-rekey.configure {
  # If you already have a package set in your flake, you can just pass it through.
  # here `pkgs.x86_64-linux` must be a package set for x86_64-linux. You only need to define those that are acutally needed.
  pkgs = self.pkgs;
  # ...
}
```


        # The package sets to use. pkgs.${system} must yield an initialized nixpkgs package set
        pkgs ? self.pkgs,
