### ISSUE TITLE
Errors: Perhaps it would be worth adding help text for when users repeatedly encounter the prompt to rekey?

### ISSUE THREAD

**Issue by plaidfinch** [oddlama/agenix-rekey#20]
When I was first getting set up using this library, I got stuck in a loop of being prompted to rekey. It turns out, I skipped the warning in step 4 of the README, *mea culpa*. But it would have been quicker to realize my error if there was help text in the "you need to rekey" message which indicated that if this error shows up repeatedly, you likely need to configure the `extra-sandbox-paths` per the README.

Hopefully this user experience note is helpful! I figure that I only get one chance to be a first-time user of a piece of software, so I'm trying to document the gotchas I encounter to smooth the way for others in the future. :)

**Comment by oddlama** [comment]
Thanks for the info!
I'll have to think about how to make this specific error better to understand. Maybe the loop can be detected somehow and then an appropriate message can be shown..

**Comment by oddlama** [comment]
This particular situation should not occur anymore with local storage mode, no configuration of extra-sandbox-paths needed :)
