### ISSUE TITLE
agenix edit produces error about "not producing attribute." 

### ISSUE THREAD

**Issue by YaroKasear** [oddlama/agenix-rekey#27]
I am having trouble getting started using this. I managed to set up my identity information and pubkeys for one of my systems.

I try to create a test secret, but when I run `agenix edit` I get the following:

`error: flake 'git+file:///home/yaro/flakes' does not provide attribute 'apps.x86_64-linux.agenix-rekey.x86_64-linux.edit', packages.x86_64-linux.agenix-rekey.x86_64-linux.edit', 'legacyPackages.x86_64-linux.agenix-rekey.x86_64-linux.edit' or 'agenix-rekey.x86_64-linux.edit'`

I don't see anything in the readme about this attribute, so I'm really confused that this means. I admit I don't know much about agenix, as I'm coming from sops-nix.

**Comment by oddlama** [comment]
Oh I'm sorry, that was kind of my mistake 😅
I've added support for flake-parts today and in between there was a broken commit that you seem to have run into.

If you update your inputs the error should go away.

**Comment by YaroKasear** [comment]
This seems to have worked. Now I'm just figuring out how this all works! Thank you.

**Comment by YaroKasear** [comment]
Actually, I'd like to reopen this issue even if I'm having a new problem. I don't think I'd like to clutter your issues tracker. 

The agenix rekey command doesn't seem to be looking relative to root but relative to the file I configured this system's localStorageDir, causing it to look in a place that doesn't exist:

`error: Cannot determine true origin of /nix/store/d6l43phvk6n2dnhpzcqv0ac68a24maqh-modules/nixos/common/systems/x86_64-linux/loki/secrets which doesn't seem to be a direct subpath of the flake directory /nix/store/mbr2d9dvkmmmgpi5yal101lxldvy4935-source. Did you make sure to specify `age.rekey.localStorageDir` relative to the root of your flake?`

I configured this in a module in ./modules/nixos/common/default.nix:

```nix
age.rekey = {
  localStorageDir = ./. + "/systems/${pkgs.system}/${config.networking.hostName}/secrets";
  masterIdentities = [ ./files/yubikey.pub ];
  storageMode = "local";
};
```

But if I understand this error correctly, putting aside the non-matching hash in the name, it's trying to look in ./modules/nixos/common/systems/x86_64-linux/loki/secrets to place the file instead of where I assume it should be doing based on the documentation's instructions: ./systems/x86_64-linux/loki/secrets.

Do I have this wrong?

**Comment by YaroKasear** [comment]
Okay, I "fixed" this by changing localStorageDir to `inputs.self + "/systems/${pkgs.system}/${config.networking.hostName}/secrets"`

I'm not sure if this is because I'm using snowfall-lib or not.

**Comment by YaroKasear** [comment]
Yeah, I'm really struggling to make this work. I can't use any relative paths with this because the agenix command will look in the wrong output folder for the secret instead of my flake root, and agenix generate took a lot of coercing to generate the file, which agenix rekey immediately deleted, saying it was an "orphan." 

I'd really like to be able to replace sops-nix with this, but following the documentation doesn't seem to be working for me.

**Comment by oddlama** [comment]
The paths seem a little fragile unfortunately, because the script must be able to know where your secrets are placed relative to your flake root (otherwise it cannot generate the files or place the new files there).

The crucial part to make this work is to never use `toString` on a path, and this includes string interpolations. So `"${somePath}/a/b"` would call `toString somePath` which is bad, because the path will then be copied to the nix store again under a new name. If you need to concatenate, always use `somePath + "/relative/path" as this will not trigger a re-copy.

So the `rekeyFile` should always be either a normal relative path like `rekeyFile = ./a/b/something.age` or a compound where you use `somePath + "/relative/part"`. Of course you may string interpolate other stuff like the `hostName`.

**Comment by oddlama** [comment]
I've found your flake in your profile. From what I can tell you are using the path concatenation correctly. But your secrets are getting cleaned by the orphaned file remover because you are using the same local storage directory for two distinct hosts (loki and loki-xorg).

You are telling agenix-rekey to rekey files for both of them, because they are two distinct hosts in `nixosConfigurations`. So agenix-rekey must be able to assume that their local storage directories are different too. You can either only tell agenix-rekey about one of them, if they are indeed the same host with the same ssh private key, or just make sure that the `localStorageDir` is set to a different value for each of them.

**Comment by YaroKasear** [comment]
These are all helpful. I'm going to shore up my `localStorageDir` and probably get rid of loki-xorg. Same machine, different profile for gaming due to using nVidia on Wayland, but with new stuff coming down to Wayland I might not need it anymore.

Thanks fir bearing with me.

**Comment by YaroKasear** [comment]
I think it works! Just want to confirm, is this what I want to see?

![Screenshot_20240530_085718](https://github.com/oddlama/agenix-rekey/assets/11284661/6048e3c2-d388-4d29-9369-0604cbd1c348)

**Comment by YaroKasear** [comment]
> The `localStorageDir` must not be the same as the one where you are storing your original secrets

I just discovered that and was about to comment. I'm going to adjust my flake here. Again, thanks for bearing with me.

**Comment by oddlama** [comment]
No worries, maybe a warning should be in place there. Your original secrets are the only thing that should be important to you, the local storage dir is more or less a implementation detail. Maybe I should add a sensible default for it.

**Comment by oddlama** [comment]
Currently there's only a NixOS module, but if you are using home manager together with nixos you can definitely just set the correct owner on the NixOS secret and use it inside home manager.

Home-manager only configurations would be a problem right now, that's definitely something we'd need to address in the future.

**Comment by YaroKasear** [comment]
Thanks, I've got this working. I have one last question.

I notice you encourage one doesn't put their rekeyed age files in their git repository. This becomes a problem since Nix refuses to evaluate any files in a Flake NOT in a git repo. I tried putting a .gitignore file in there so it won't go up to Github from my main machine whenever I use agenix rekey, but now Nix complains about not finding the rekeyed files because they can't be added to Git.

Is there a solution to this or am I going to have to maintain my Flake separately from my deployment of that Flake on the same machine, which is a bit of a pain?

**Comment by YaroKasear** [comment]
My bad, I think I misinterpreted something, now that I can't seem to find it in the README.

It does rekey and deploy secrets! Hooray! Except it fails on boot, so I'm trying to find why. My leading hunch is impermanence is putting persistent data in *after* agenix-rekey is supposed to be decrypting the secrets, so there's no private key yet for agenix-rekey to use. Unless you think it could be something else.

**Comment by oddlama** [comment]
Yeah, if you use impermanence you probably want something like this: https://github.com/oddlama/nix-config/blob/1424778bc2bc5213f8d66e48464b153658be4323/config/impermanence.nix#L18-L19 (not related to rekeying though :) )

**Comment by YaroKasear** [comment]
That fixed it. I'm now properly using agenix-rekey. Thanks for guiding me here.
