### ISSUE TITLE
agenix edit failure

### ISSUE THREAD

**Issue by YaroKasear** [oddlama/agenix-rekey#30]
I update my Flake today, and I was working on adding a new secret, but running `agenix edit` produced this error:

```console
error: builder for '/nix/store/n6q3z6k66zpz35cvqczd6zpv4rhg68x1-ageWrapper.drv' failed with exit code 1;
       last 7 log lines:
       >
       > In /nix/store/6j670hpqw2034lda12ly9gb9w1xs58c7-ageWrapper/bin/ageWrapper line 21:
       > for file in '/nix/store/q3sz5b3dknlr8d1hg9iwdf0lsck34xky-kgl3n0n266cf1vfcvmb555kxdk479099-source/modules/nixos/common/files/yubikey.pub'; do
       >             ^-- SC2041 (warning): This is a literal string. To run as a command, use $(..) instead of '..' . 
       >
       > For more information:
       >   https://www.shellcheck.net/wiki/SC2041 -- This is a literal string. To run ...
       For full logs, run 'nix log /nix/store/n6q3z6k66zpz35cvqczd6zpv4rhg68x1-ageWrapper.drv'.
error: 1 dependencies of derivation '/nix/store/703isiasbd05il8yl7nh9ywaxzh1ifb6-agenix-edit.drv' failed to build
```

Reverting my flake.lock to the previous version clears the error. There might be a breaking change somewhere in agenix-rekey.

**Comment by Lukas-C** [comment]
Seems like this is an edgecase that slipped by during my testing of #28. However I also just saw that @oddlama seems to have run into your issue already. Should be fixed in https://github.com/oddlama/agenix-rekey/commit/4551006c2807ab361ea4db5e171afb4798da4fc2, sorry for the inconvenience!

**Comment by oddlama** [comment]
Yep I just fixed that, sorry for the inconveniences 😅
