### ISSUE TITLE
Agenix rekey refuses to work, says storageMode is not "local" when it is.

### ISSUE THREAD

**Issue by YaroKasear** [oddlama/agenix-rekey#42]
So, I recently reinstalled NixOS... and agenix is refusing to rekey me, erroneously claiming that my secrets storage mode is "derivation."

This is incorrect. I can clearly see in my flake I set it to "local."

Because of this I am unable to rekey my secrets and I'm locked out of my system as a result.

```
Collecting information about hosts. This may take a while...
warning: Git tree '/persistent/flakes' is dirty
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'agenix-rekey'
         whose name attribute is located at /nix/store/9j4ygbyvnmqfbasbsyf739gzadnd6b5q-source/pkgs/stdenv/generic/make-derivation.nix:333:7

       … while evaluating attribute 'text' of derivation 'agenix-rekey'
         at /nix/store/9j4ygbyvnmqfbasbsyf739gzadnd6b5q-source/pkgs/build-support/trivial-builders/default.nix:103:17:
          102|       ({
          103|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                 ^
          104|         passAsFile = [ "text" ]

       … while evaluating the option `age.rekey.storageMode':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: evaluation aborted with the following error message: '!!!
       agenix-rekey now supports storing rekeyed secrets locally instead of as a derivation.
       You should explicitly specify the desired storage mode for each host!

       Got no time right now? Set this to keep the old behavior:

           age.rekey.storageMode = "derivation";

       If you have just installed agenix-rekey, chose "local" and ignore this message:

           # Choose "local" (new behavior) or "derivation" (old behavior).
           age.rekey.storageMode = "local";
           # Choose a directory to store the rekeyed secrets for this host.
           # This cannot be shared with other hosts. Please refer to this path
           # from your flake's root directory and not by a direct path literal like ./secrets
           age.rekey.localStorageDir = ./. + "/secrets/rekeyed/minimal";

       The new local storage mode is more pure and simpler. It allows building your system without access to the
       (yubi)key, for example in a CI environment. Depending on your threat-model it might be considered less secure,
       especially when your repo is public and one your host-keys leaks. Visit the README (https://github.com/oddlama/agenix-rekey)
       and search check the section on 'Storage Modes' for more information.

       To keep the old behavior, select "derivation". This message will be removed end of 2024 so we can choose an upstream default.
       '
```

**Comment by oddlama** [comment]
> [...] claiming that my secrets storage mode is "derivation." This is incorrect. I can clearly see in my flake I set it to "local."

Do you have a link to your config? The message seems to indicate that whatever you set wasn't actually the option but something else - thus causing the real option to fall back to the default, as indicated by the warning message that appeared.

**Comment by YaroKasear** [comment]
> > [...] claiming that my secrets storage mode is "derivation." This is incorrect. I can clearly see in my flake I set it to "local."
> 
> Do you have a link to your config? The message seems to indicate that whatever you set wasn't actually the option but something else - thus causing the real option to fall back to the default, as indicated by the warning message that appeared.

Certainly.

https://github.com/YaroKasear/flakes This is a link to my flake.

Specifically, I was setting Loki back up: https://github.com/YaroKasear/flakes/blob/main/systems/x86_64-linux/loki/default.nix (Note that it enables the united.common module.

That module is here: https://github.com/YaroKasear/flakes/blob/main/modules/nixos/common/default.nix As you can see, it has the storageMode set to "local."

This worked before. And when I was trying to troubleshoot this, I noticed on Deimos (One of the other "common" module consumers.) also had this issue, and nothing had changed in its configuration that was relevant to agenix-rekey, but trying to rekey on the server also prompted this error. 

I also tried setting age.rekey.storageMode DIRECTLY into Loki's default.nix and it didn't change the outcome. If this isn't an issue introduced in an update to agenix-rekey, something somewhere did cause a breakage, and I don't know what it was.

**Comment by YaroKasear** [comment]
I tracked it down by doing a git bisect.

I had created a new system configuration, "minimal."

It's not meant to actually use agenix at all, but it refused to evaluate if I didn't include it. 

It doesn't include the common module, so it wasn't defining storageMode or localStorageDir. Once I added those settings my rekey started working again. 

Indeed, the bug was on my end.

**Comment by YaroKasear** [comment]
I'll follow this up. Consider it a mini feature request, perhaps. Is it possible to have agenix-rekey say what system configuration it's evaluating when there's an error like this? Make it clear what it's looking at when it says a setting is wrong?

**Comment by oddlama** [comment]
It's unfortunately not super easy to do this, since all the evaluation is done by nix and not agenix-rekey. We just evaluate the .#agenix-rekey flake output in the generated script, and that will of course fail if anything passed in there cannot evaluate.

To my knowledge there's no trivial way to add additional information to the bottom of the error stack to an expression that is supplied by the user and which we don't control directly. I may be wrong though, so if anyone else has a solution I'd love to add this.
