### ISSUE TITLE
Add support for Git submodules in agenix CLI or a way to use a private repo

### ISSUE THREAD

**Issue by Toomoch** [oddlama/agenix-rekey#46]
Hi, I was trying to use agenix-rekey with a private Git repo to store all the secrets. I wanted to use the local storage mode and the agenix CLI has no option to specify `?submodules=1'`, so naturally, `agenix rekey` fails with `error: age.secrets.secret1.rekeyFile (/nix/store/kpwc8jii02kn02a1fs9hwvz0a0y2shb0-source/private/test.age) doesn't exist. Have you added it to git?` as it doesn't import the `private` submodule. Is there any way I can use agenix-rekey with a private repo to store the secrets?

There could also be a way to declare a localStorageDir imperatively, so that it gets added in another repo cloned locally.

**Comment by oddlama** [comment]
Good point! I see you already made a PR to fix this :)
