### ISSUE TITLE
Unreachable identity after reboot

### ISSUE THREAD

**Issue by Bohreromir** [oddlama/agenix-rekey#52]
I'm getting the following error after a boot. If i manually update the host with `nixos-rebuild --target-host ...` the secrets get populated and are accessible. Only after reboot they disappear again.
Do you have any idea, what that could be?

No difference between using both storage modes
The file /home/user/.ssh/id_ed25519 is accessible after boot

```
[   43.707924] stage-2-init: [agenix] WARNING: config.age.identityPaths entry /home/user/.ssh/id_ed25519 not present!
[   43.708171] stage-2-init: decrypting '/nix/store/hbc8vvb4f9a4drh5pgn8ps1p8g1mr1ch-agenix-rekey-host-secrets/pass.age' to '/run/agenix.d/1/pass'...
[   43.708280] stage-2-init: [agenix] WARNING: no readable identities found!
[   43.727257] stage-2-init: age: error: no identity matched any of the recipients
[   43.727393] stage-2-init: age: report unexpected or unhelpful errors at https://filippo.io/age/report
[   43.729024] stage-2-init: chmod: cannot access '/run/agenix.d/1/pass.tmp': No such file or directory
[   43.730520] stage-2-init: mv: cannot stat '/run/agenix.d/1/pass.tmp': No such file or directory
```

**Comment by oddlama** [comment]
That's looks like it is not related to agenix-rekey, but an issue with either agenix or the specific way you are using it. Anything that occurs at runtime is handled by agenix itself. I think you should reopen the issue over on the [agenix](https://github.com/ryantm/agenix) repo, people over there might know what's going on

**Comment by Bohreromir** [comment]
Aparently my /home was being mounted to late.
I added `fileSystems."/home".neededForBoot = true;` to my config and it worked again.
I'm still wondering what triggered the need for that, but at least its working now.
